### ISSUE TITLE
大佬，求code！

### ISSUE THREAD

**Issue by FIRE-MOS** [wangzhuo2019/SSAN#2]

**Comment by futureisatyourhand** [comment]
可能作者实验有问题，不公开代码哈哈哈

**Comment by FIRE-MOS** [comment]
666，不太可能吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qian ***@***.***&gt;; 
发送时间: 2022年5月5日(星期四) 中午1:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangzhuo2019/SSAN] 大佬，求code！ (Issue #2)





 
可能作者实验有问题，不公开代码哈哈哈
