### ISSUE TITLE
Request for supplementary materials

### ISSUE THREAD

**Issue by parthagar** [wangzhuo2019/SSAN#5]

**Comment by wangzhuo2019** [comment]
Supplementary materials will be provided in [cvf.](https://openaccess.thecvf.com/).

**Comment by parthagar** [comment]
Thanks @wangzhuo2019 . Here is the direct link for it: https://openaccess.thecvf.com/content/CVPR2022/supplemental/Wang_Domain_Generalization_via_CVPR_2022_supplemental.pdf

**Comment by parthagar** [comment]
We found some discrepancies in the network architecture i.e. architecture in the paper and the code are different at some places. Which one is the correct one?
