### ISSUE TITLE
SCL

### ISSUE THREAD

**Issue by PangziZhang523** [wangzhuo2019/SSAN#6]
"To make a comparison between them, the experiment of w/ SCL is conducted by implementing contrastive learning on selfassembly
directly." 
这个实验具体是想证明什么，能详细说一下吗？谢谢

**Comment by wangzhuo2019** [comment]
主要是想和直接使用对比学习方式的方法做对比实验。如这篇文章中的scl方式：Improved Detection of Face Presentation Attacks Using Image Decomposition.
